version: '3.9'

services:
  mediaplayer:
    container_name: mediaplayer
    restart: always
    image: caddy:2.3.0-alpine
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
    volumes:
      - ${PWD}/out:/usr/share/caddy/out:ro
      - ${PWD}/mp3:/usr/share/caddy/mp3:ro
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile:ro